authors/urls.py
from django.urls import path
from authors import views

app_name = 'authors'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('register/created/', views.register_created, name='created'),
]

project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("recipes.urls")),
    path('authors/', include("authors.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path
from . import views

app_name = "recipes"

urlpatterns = [
    path('', views.home, name='home'),
    path('recipes/search/', views.search, name='search'),
    path('recipes/category/<int:category_id>/',
         views.category, name='category'),
    path('recipes/<int:id>/', views.recipes, name='itens'),
]

authors/models.py
from django.db import models

# Create your models here.

recipes/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name


class Recipes(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    slug = models.SlugField(unique=True)
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=65)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=65)
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    is_published = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    cover = models.ImageField(upload_to='recipes/covers/%Y/%m/%d/')
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, blank=True, default=None,  # noqa: E501
    )
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True, default=None,
    )

    def __str__(self):
        return self.title

authors/forms.py
from django import forms
from django.contrib.auth.models import User


class RegisterForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password'
        ]

authors/views.py
from django.shortcuts import render, redirect
from authors.forms import RegisterForm
from django.http import Http404


def register_view(request):
    register_form_data = request.session.get('register_form_data', None)
    form = RegisterForm(register_form_data)

    return render(request, 'authors/pages/register_view.html', context={
        'form': form
    })


def register_created(request):
    if not request.POST:
        raise Http404()

    POST = request.POST
    request.session['register_form_data'] = POST

    return redirect('authors:register')

recipes/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404
from django.http import Http404
from recipes.models import Recipes
from django.db.models import Q
from utils.pagination import make_pagination
import os

PER_PAGE = os.environ.get("PER_PAGE", 3)


def home(request):
    recipes = Recipes.objects.filter(
        is_published=True,
    ).order_by('-id')

    pagination_range, page_obj = make_pagination(
        request, recipes, PER_PAGE)

    return render(request, "recipes/pages/home.html", context={
        'recipes': page_obj,
        'pagination_range': pagination_range
    })


def category(request, category_id):
    recipes = get_list_or_404(
        Recipes.objects.filter(
            category__id=category_id,
            is_published=True,
        ).order_by('-id')
    )

    pagination_range, page_obj = make_pagination(
        request, recipes, PER_PAGE)

    return render(request, "recipes/pages/home.html", context={
        'recipes': page_obj,
        'pagination_range': pagination_range
    })


def recipes(request, id):
    recipes = get_object_or_404(
        Recipes.objects.filter(
            pk=id,
            is_published=True,
        )
    )
    return render(request, "recipes/pages/recipes-view.html", context={
        'recipe': recipes,
        'is_detail_page': True,
    })


def search(request):
    search_term = request.GET.get('q', '').strip()

    if not search_term:
        raise Http404()

    recipes = Recipes.objects.filter(
        Q(
            Q(title__icontains=search_term) |
            Q(description__icontains=search_term),
        ),
        is_published=True
    ).order_by('-id')

    pagination_range, page_obj = make_pagination(
        request, recipes, PER_PAGE)

    return render(request, 'recipes/pages/search.html', context={
        'search_term': search_term,
        'recipes': page_obj,
        'pagination_range': pagination_range,
        'additional_url_query': f'&q={ search_term }'
    })

authors/templates/authors/pages/register_view.html
{% extends "global/base.html" %}

{% block title %}Register |{% endblock title %}

{% block content %}
    <div class="main-content center container">
        <h2>Recipes {{ request.session.number }} </h2>
    </div>
    
    <div class="main-content container">
        <form action="{% url "authors:created" %}" method="POST">
            {% csrf_token %}

            <div class="form-content form-content-grid">
                {% for field in form %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}"> {{ field.label }} </label>
                        {{ field }}

                        {% if field.help_text %}
                            <p class="help-text">{{ field.help_text }}</p>
                        {% endif %}

                        {{ field.errors }}
                    </div>
                {% endfor %}
            </div>

            <div class="form-content container">
                <div class="form-group">
                    <button type="submit">Send</button>
                </div>
            </div>
        </form>
    </div>


{% endblock content %}

recipes/templates/recipes/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>

</body>

</html>

recipes/templates/recipes/pages/home.html
{% extends "global/base.html" %}

{% block content %}
<div class="main-content main-content-list container">
    {% for recipe in recipes %}
    {% include "recipes/partials/recipe-item.html" %}
    {% empty %}
    <div class="center">
        <h1>No recipes found here!</h1>
    </div>
    {% endfor %}
</div>
{% endblock content %}

recipes/templates/recipes/pages/recipes-view.html
{% extends "global/base.html" %}

{% block title %} {{ recipe.title }} | {% endblock title %}

{% block content %}
<div class="main-content main-content-detail container">
    {% include "recipes/partials/recipe-item.html" %}
</div>
{% endblock content %}

recipes/templates/recipes/pages/search.html
{% extends "global/base.html" %}

{% block title %}Search for {{ search_term }} | {% endblock title %}

{% block content %}
<div class="main-content main-content-list container">
    {% for recipe in recipes %}
    {% include "recipes/partials/recipe-item.html" %}
    {% empty %}
    <div class="center">
        <h1>No recipes found here!</h1>
    </div>
    {% endfor %}
</div>
{% endblock content %}

recipes/templates/recipes/partials/header.html
<header class="main-header-container">
    <div class="main-header container">
        <h1>
            <a href="/" class="main-logo">
                <i class="fas fa-utensils main-logo-icon"></i>
                <span class="main-logo-text">Recipes</span>
            </a>
        </h1>
    </div>
</header>

recipes/templates/recipes/partials/paginator.html
{% if recipes.has_other_pages %}
    <div class="container paginator">
        <div class="pagination-content">
            {% if pagination_range.first_page_out_of_range %}
                <a class="page-link page-item" href="?page=1{{ additional_url_query }}">1</a>
                <span class="page-item">...</span>
            {% endif %}
            {% for page in pagination_range.pagination %}
                {% if pagination_range.current_page == page %}
                    <a class="page-link page-item page-current" href="?page={{ page }}{{ additional_url_query }}">{{ page }}</a>
                {% else %}
                    <a class="page-link page-item" href="?page={{ page }}{{ additional_url_query }}">{{ page }}</a>
                {% endif %}
            {% endfor %}
            {% if pagination_range.last_page_out_of_range %}
                <span class="page-item">...</span>
                <a class="page-link page-item" href="?page={{ pagination_range.total_pages }}{{ additional_url_query }}"> {{ pagination_range.total_pages }} </a>
            {% endif %}
        </div>
    </div>
{% endif %}

recipes/templates/recipes/partials/recipe-item.html
<div class="recipe recipe-list-item">
    <div class="recipe-cover">
        <img src="{{ recipe.cover.url }}" alt="Temporário" class="portrait">
    </div>

    <div class="recipe-title-container">
        <h2 class="recipe-title">{{ recipe.title }}</h2>
    </div>

    <div class="recipe-author">
        <span class="recipe-author-item">
            <i class="fas fa-user"></i>
            {% if recipe.author is not None %}
            {% if recipe.author.first_name %}
            {{ recipe.author.first_name }} {{ recipe.author.last_name }}
            {% else %}
            {{ recipe.author.username }}
            {% endif %}
            {% else %}
            Desconhecido
            {% endif %}
        </span>

        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{ recipe.created_at|date:'d/m/Y' }} às {{ recipe.created_at|date:'H:i' }}
        </span>

        {% if recipe.category.id is not None %}
        <span class="recipe-author-item">
            <a href="{% url 'recipes:category' recipe.category.id %}">
                <i class="fas fa-layer-group"></i>
                <span>{{ recipe.category.name }}</span>
            </a>
        </span>
        {% endif %}
    </div>

    <div class="recipe-content">
        <p>{{ recipe.description }}</p>
    </div>

    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i>Preparo</h3>
            <div class="recipe-meta-text">
                {{ recipe.preparation_time }} {{ recipe.preparation_time_unit }}
            </div>
        </div>

        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i>Porções</h3>
            <div class="recipe-meta-text">
                {{ recipe.servings }} {{ recipe.servings_unit }}
            </div>
        </div>
    </div>

    {% if is_detail_page is not True %}
    <footer class="recipe-footer">
        <a class="recipe-read-more button button-dark button-full-width" href="{% url 'recipes:itens' recipe.id %}">
            <i class="fas fa-eye"></i>
            <span>Ver mais...</span>
        </a>
    </footer>
    {% endif %}

    {% if is_detail_page %}
    <div class="preparation-steps">
        {% if recipe.preparation_steps_is_html is not True %}
        <p>{{ recipe.preparation_steps|linebreaksbr }}</p>
        {% else %}
        <p>{{ recipe.preparation_steps|safe }}</p>
        {% endif %}
    </div>
    {% endif %}

</div>

recipes/templates/recipes/partials/search.html
<div class="search-container">
    <div class="container">
        <form action="{% url "recipes:search" %}" method='GET' class="search-form">
            <input type="search" name="q" id="search" class="search-input" value="{{ search_term }}"  placeholder="Digite aqui sua pesquisa" required>
            <button type="submit" class="search-button"><i class="fas fa-search"></i></button>
        </form>
    </div>
</div>